### ISSUE TITLE
Seems not able to convert a universal joint

### ISSUE THREAD

**Issue by CarlsonGYC** [gazebosim/gz-usd#45]
I am trying to convert a model with universal joints:
This is the joint sdf code:

<joint name='cable_1_joint_payload' type='universal'>
      <pose relative_to="payload">
        0.15 0.0 -0.025  0 1.5707963267948966 0.0
      </pose>
      <parent>payload</parent>
      <child>cable_1_segment_0_p</child>
      <axis>
        <xyz>0 1 0</xyz>
      </axis>
      <axis2>
        <xyz>1 0 0</xyz>
      </axis2>
    </joint>
    
    
    However, when I run the convert code, an error occured:
    (ros) carlson@carlson:~/gz-usd/build/bin$ ./sdf2usd /home/carlson/ros/multi_cable/src/multi_cable/sdf/cable_Mul_new.sdf ./cable_Mul_new.usd
The following errors occurred when parsing model [flexible_cable]:
Error Code 2: Msg: Error parsing joint [cable_1_joint_payload].
Error Code 5: Msg: Joint type is either invalid or not supported.

Is it possible to convert a universal joint?

**Comment by ahcorde** [comment]
In this file [1] you can check which joints are supported 

[1] https://github.com/gazebosim/gz-usd/blob/main/src/usd_parser/USDJoints.cc

**Comment by CarlsonGYC** [comment]
> In this file [1] you can check which joints are supported
> 
> [1] https://github.com/gazebosim/gz-usd/blob/main/src/usd_parser/USDJoints.cc

Thank you, I will try two revolute joint to replace a universal joint then.

**Comment by ahcorde** [comment]
I will close the issue, feel free to open another one if you have some other issues
